# Book settings
######################################################################################
# Book settings
title: "ATSC 301"
author: Philip Austin
email: paustin@eoas.ubc.ca
description: >- # this means to ignore newlines until "baseurl:"
  Website for EOAS ATSC 301

execute:
  execute_notebooks: 'cache'

parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - dollarmath
    - html_admonition
    - html_image

exclude_patterns: ["*ipynb"]

repository:
  url: https://github.com/phaustin/a301_2020
  branch: master
  path_to_book: .

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  jupyterhub_url: https://jupyter.eoastest.xyz

html:
  home_page_in_navbar: true
  baseurl: https://hub.eoastest.xyz/a301
