name: notebook
channels:
  - eoas_ubc
  - conda-forge
dependencies:
  # NOTE: pip required for running tests in this repo
  - python=3.11
  - pyhdf
  - numpy
  - pip
  - cartopy>0.21
  - pyresample
  - netcdf4
  - jupyterlab
  - jupytext
  - pythia-datasets
  - pytest
  - rasterio
  - rioxarray
  - pystac-client
  - shapely
  - seaborn
  - scikit-image
  - goes2go
# conda-lock --kind explicit -f environment_trun.yml -p linux-64
