name: notebook
channels:
  - eoas_ubc
  - conda-forge
dependencies:
  # NOTE: pip required for running tests in this repo
  - python
  - pyhdf
  - numpy
  - pip
  - jupytext
  - jupyterhub=2.3.1
  - cartopy>0.21
  - pyresample
  - netcdf4
  - jupyterlab
  - dask
# conda-lock --kind explicit -f environment_trun.yml -p linux-64
